import { NextResponse } from "next/server"

export async function GET() {
  // Sample data. Replace with Google Scholar integration if available.
  const publications = [
  {
    id: "J1",
    title: "Machine learning concepts and its applications for prediction of diseases based on drug behaviour: An extensive review",
    authors: "D. P. Singh, B. Kaushik",
    venue: "Chemometrics and Intelligent Laboratory Systems",
    year: 2022,
    doi: "https://doi.org/10.1016/j.chemolab.2022.104637",
    type: "Journals",
  },
  {
    id: "J2",
    title: "DWUT-MLP: Classification of anticancer drug response using various feature selection and classification techniques",
    authors: "D. P. Singh, A. Gupta, B. Kaushik",
    venue: "Chemometrics and Intelligent Laboratory Systems",
    year: 2022,
    doi: "https://doi.org/10.1016/j.chemolab.2022.104562",
    type: "Journals",
  },
  {
    id: "J3",
    title: "A systematic literature review for the prediction of anticancer drug response using various machine-learning and deep-learning techniques",
    authors: "D. P. Singh, B. Kaushik",
    venue: "Chemical Biology & Drug Design",
    year: 2022,
    doi: "https://doi.org/10.1111/cbdd.14164",
    type: "Journals",
  },
  {
    id: "J4",
    title: "CTDN (convolutional temporal based deep-neural network): an improvised stacked hybrid computational approach for anticancer drug response prediction",
    authors: "D. P. Singh, B. Kaushik",
    venue: "Computational Biology and Chemistry",
    year: 2023,
    doi: "https://doi.org/10.1016/j.compbiolchem.2023.107868",
    type: "Journals",
  },
  {
    id: "J5",
    title: "Image-based automatic segmentation of leaf using clustering algorithm",
    authors: "S. Sharma, C. Chakraborty, D. P. Singh, S. Mahajan, A. K. Pandit",
    venue: "International Journal of Nanotechnology",
    year: 2022,
    doi: "https://doi.org/10.1504/IJNT.2022.128939",
    type: "Journals",
  },
  {
    id: "J6",
    title: "Advanced multi-virus genome sequence classification using artificial intelligence techniques",
    authors: "D. Swain, K. Patel, K. Shah, M. Mistry, M. Kumar, D. P. Singh, V. C. Gerogiannis, A. Kanavos, B. Acharya",
    venue: "Intelligent Decision Technologies",
    year: 2025,
    doi: "https://doi.org/10.1177/18724981241312343",
    type: "Journals",
  },
  {
    id: "J7",
    title: "A Comprehensive Review of Various Machine Learning and Deep Learning Models for Anti-Cancer Drug Response Prediction: Comparative Analysis with Existing State of the Art Methods",
    authors: "D. P. Singh, P. Kour, T. Banerjee, D. Swain",
    venue: "Archives of Computational Methods in Engineering",
    year: 2025,
    doi: "https://doi.org/10.1007/s11831-025-10255-2",
    type: "Journals",
  },
  {
    id: "J8",
    title: "CICADA (UCX): A Novel Approach for Automated Breast Cancer Classification through Aggressiveness Delineation",
    authors: "D. P. Singh, T. Banerjee, P. Kour, D. Swain, Y. Narayan",
    venue: "Computational Biology and Chemistry",
    year: 2025,
    doi: "https://doi.org/10.1016/j.compbiolchem.2025.108368",
    type: "Journals",
  },
  {
    id: "J9",
    title: "LLN-enhanced UVEX net: a hybrid deep learning approach for precise segmentation of thoracic organs at risk in CT images for radiotherapy planning",
    authors: "D. P. Singh, T. Banerjee, M. Ashok, S. Mahajan",
    venue: "International Journal of Intelligent Engineering Informatics",
    year: 2025,
    type: "Journals",
  },
  {
    id: "J10",
    title: "Optimising brain tumour segmentation and classification with an enhanced CNN model on the BraTS-GoAT 2024 dataset",
    authors: "V. Satushe, S. Vyas, S. Metkar, D. P. Singh",
    venue: "International Journal of Intelligent Engineering Informatics",
    year: 2025,
    type: "Journals",
  },
  {
    id: "J11",
    title: "AI in MRI Brain Tumor Diagnosis: A Systematic Review of Machine Learning and Deep Learning Advances (2010–2025)",
    authors: "V. Satushe, S. Vyas, S. Metkar, D. P. Singh",
    venue: "Chemometrics and Intelligent Laboratory Systems",
    year: 2025,
    doi: "https://doi.org/10.1016/j.chemolab.2025.105414",
    type: "Journals",
  },
  {
    id: "J12",
    title: "Comparison based on transfer learning and fusion of deep learning models for brain cancer classification",
    authors: "Y. Narayan, A. P. Pasupulla, D. Kumar, K. R. Chandra, R. M. Singh, P. Charan, D. P. Singh",
    venue: "Multimedia Tools and Applications",
    year: 2025,
    doi: "https://doi.org/10.1007/s11042-025-20884-1",
    type: "Journals",
  },
  {
    id: "J13",
    title: "Predictive Modeling for Bank Loan Approval: From Data to Decisions",
    authors: "D. P. Singh, A. Khare, P. N, R. Lal, S. S. Chauhan, K. C.",
    venue: "Procedia Computer Science",
    year: 2025,
    doi: "https://doi.org/10.1016/j.procs.2025.04.097",
    type: "Journals",
  },
  {
    id: "J14",
    title: "A Comprehensive Study on Deep Learning Models for the Detection of Diabetic Retinopathy using Pathological Images",
    authors: "D. P. Singh, T. Banerjee, S. Mahajan, K. R. Chandra, R. Kumar, S. Phani, P. Kour, Y. Narayan, G. Kour, L. Mukhija, D. Swain, M. Ashok",
    venue: "Archives of Computational Methods in Engineering",
    year: 2025,
    doi: "https://doi.org/10.1007/s11831-025-10315-7",
    type: "Journals",
  },
  {
    id: "J15",
    title: "A novel hybrid deep learning approach combining deep feature attention and statistical validation for enhanced thyroid ultrasound segmentation",
    authors: "T. Banerjee, D. P. Singh, D. Swain, S. Mahajan, S. Kadry, J. Kim",
    venue: "Scientific Reports",
    year: 2025,
    doi: "https://doi.org/10.1038/s41598-025-12602-6",
    type: "Journals",
  },
  {
    id: "J16",
    title: "A novel unified Inception-U-Net hybrid gravitational optimization model (UIGO) incorporating automated medical image segmentation and feature selection for liver tumor detection",
    authors: "T. Banerjee, D. P. Singh, P. Kour, D. Swain, S. Mahajan, S. Kadry, J. Kim",
    venue: "Scientific Reports",
    year: 2025,
    doi: "https://doi.org/10.1038/s41598-025-14333-0",
    type: "Journals",
  },

  // ================= Conference Publications =================
  {
    id: "C1",
    title: "Anti-Drug Response and Drug Side Effect Prediction Methods: A Review",
    authors: "D. P. Singh, A. Gupta, B. Kaushik",
    venue: "Computational Intelligence and Data Analytics, Springer",
    year: 2022,
    doi: "https://doi.org/10.1007/978-981-19-3391-2_11",
    type: "Conferences",
  },
  {
    id: "C2",
    title: "Anti-drug Response Prediction: A Review of the Different Supervised and Unsupervised Learning Approaches",
    authors: "D. P. Singh, A. Gupta, B. Kaushik",
    venue: "Machine Intelligence and Smart Systems, Springer",
    year: 2022,
    doi: "https://doi.org/10.1007/978-981-16-9650-3_29",
    type: "Conferences",
  },
  {
    id: "C3",
    title: "Rice type classification using RBF Kernel Svm",
    authors: "D. P. Singh, A. Sharma, D. Swain, V. Sathya, J. S. Kumar, M. Upadhyaya",
    venue: "Hybrid and Advanced Technologies, CRC Press",
    year: 2025,
    doi: "https://doi.org/10.1201/9781003559139",
    type: "Conferences",
  },
  {
    id: "C4",
    title: "Dragon fly algorithm-based feature selection for airline customer satisfaction",
    authors: "D. P. Singh, R. Sivaraman, P. Verma, A. Khare, K. Suresh, P. S. Chandel",
    venue: "Hybrid and Advanced Technologies, CRC Press",
    year: 2025,
    doi: "https://doi.org/10.1201/9781003559139",
    type: "Conferences",
  },
  {
    id: "C5",
    title: "Application of neural network in analysis of stock market prediction based on VG16-CNN-SVM model",
    authors: "D. P. Singh, R. Kumar, S. Yadav, A. T. Karnawat, S. Bandi, A. Raj",
    venue: "Hybrid and Advanced Technologies, CRC Press",
    year: 2025,
    doi: "https://doi.org/10.1201/9781003559139",
    type: "Conferences",
  },
  {
    id: "C6",
    title: "A novel approach to constructing features and models for intrusion detection systems using SAE-ELM model",
    authors: "D. P. Singh, V. W. Gangane, P. Sukumar, J. Kaushal, N. Nishant, H. Patil",
    venue: "Hybrid and Advanced Technologies, CRC Press",
    year: 2025,
    doi: "https://doi.org/10.1201/9781003559139",
    type: "Conferences",
  },
  {
    id: "C7",
    title: "Performance Analysis of ECG Disease Classification using SVM classifier",
    authors: "D. P. Singh, A. P. Pasupulla, A. Shanko, N. P, N. Neha, R. M. Singh",
    venue: "IEEE IATMSI",
    year: 2024,
    doi: "10.1109/IATMSI60426.2024.10502948",
    type: "Conferences",
  },
  {
    id: "C8",
    title: "Optimizing Virtual Machine Migration Technique for Cloud Computing",
    authors: "D. P. Singh, D. Kumar, H. N. Prajapati, R. Sivaraman, M. Dwivedi, N. N. Das",
    venue: "IEEE ICCCNT",
    year: 2024,
    doi: "10.1109/ICCCNT61001.2024.10724722",
    type: "Conferences",
  },
  {
    id: "C9",
    title: "An Energy Efficient Naïve Bayes-based Clustering Protocol for Wireless Sensor Network",
    authors: "D. P. Singh, P. Charan, D. Pasrija, D. S. Shyamal, K. Suresh, V. V. Priya",
    venue: "IEEE IATMSI",
    year: 2024,
    doi: "10.1109/IATMSI60426.2024.10502529",
    type: "Conferences",
  },
  {
    id: "C10",
    title: "Improved Pulse Coupled Neural Network based on Maximize SNR for Vessel Extraction",
    authors: "D. P. Singh, R. M. Singh, T. Gopi, D. Deepa, K. P. Gandhi, D. Kumar",
    venue: "IEEE APCI",
    year: 2024,
    doi: "10.1109/APCI61480.2024.10617283",
    type: "Conferences",
  },
  {
    id: "C11",
    title: "A Review of Plant Disease Identification using Computational Techniques",
    authors: "D. P. Singh, U. Norboeva, P. Jagadeesan, L. B. Abhang, J. S. Kumar, V. V. Priya",
    venue: "IEEE TIACOMP",
    year: 2024,
    doi: "10.1109/TIACOMP64125.2024.00086",
    type: "Conferences",
  },
  {
    id: "C12",
    title: "Enhancing enterprise human resource management: Predicting workers' stress for improved workplace satisfaction using a hybrid deep transfer learning approach",
    authors: "D. P. Singh, K. Gupta, N. Singh, M. V. Unni, S. Jayasudha, A. Chauhan",
    venue: "Hybrid and Advanced Technologies, CRC Press",
    year: 2025,
    doi: "https://doi.org/10.1201/9781003559139",
    type: "Conferences",
  },
  {
    id: "C13",
    title: "Image Forgery Detection and Classification using Deep Learning",
    authors: "D. P. Singh, V. K. Nair, R. M. Singh, P. Bafna, M. Vedaraj, V. V. Priya",
    venue: "IEEE OTCON",
    year: 2024,
    doi: "10.1109/OTCON60325.2024.10688184",
    type: "Conferences",
  },
  {
    id: "C14",
    title: "Emerging Trends of Artificial Intelligence in Detecting Neurodegeneration",
    authors: "D. P. Singh, B. Kaushik, Y. F. Khan, A. Chadha, A. Mahajan, A. Jandwani, G. S. Narula",
    venue: "IC4S 2023, Springer",
    year: 2023,
    doi: "https://doi.org/10.1007/978-981-97-2550-2_42",
    type: "Conferences",
  },
  {
    id: "C15",
    title: "Enhancing Marketing Strategies: Analyzing Customer Behavior in Banking through Data Analysis and Machine Learning",
    authors: "D. P. Singh, M. Manjari, D. Jain, S. B. Uppal, R. Kumar, P. Goel",
    venue: "IEEE TIACOMP",
    year: 2024,
    doi: "10.1109/TIACOMP64125.2024.00085",
    type: "Conferences",
  },
  {
    id: "C16",
    title: "Isolated Word Recognition and Feature Extraction Using Machine Learning",
    authors: "D. P. Singh, M. Rani, S. Kumari, R. Kumar, V. V. Priya, R. M. Singh",
    venue: "International Conference on Emerging Applications of Information Technology, Springer",
    year: 2024,
    doi: "https://doi.org/10.1007/978-981-97-7532-3_3",
    type: "Conferences",
  },
];

  return NextResponse.json(publications)
}
